version: '2'
services: 
  web:
    image: node:7.2
    ports: 
      - "8001:8001"
    volumes: 
      - ./:/app
    environment:
      PORT: '8001'
      AMQP_URI: 'amqp://rabbitmq'
    depends_on:
      - rabbitmq
    entrypoint: 'node /example'
  rabbitmq:
    image: rabbitmq:3.6.0-management
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: rabbitmq